/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as ChatSessionIdRouteImport } from './routes/chat/$sessionId'
import { Route as BuilderWizardRouteImport } from './routes/builder/wizard'
import { Route as BuilderForgeRouteImport } from './routes/builder/forge'
import { Route as BotsBotIdRouteRouteImport } from './routes/bots/$botId/route'
import { Route as BotsBotIdIndexRouteImport } from './routes/bots/$botId/index'
import { Route as BotsBotIdSoulRouteImport } from './routes/bots/$botId/soul'
import { Route as BotsBotIdSkillsRouteImport } from './routes/bots/$botId/skills'
import { Route as BotsBotIdSettingsRouteImport } from './routes/bots/$botId/settings'
import { Route as BotsBotIdChatRouteImport } from './routes/bots/$botId/chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderWizardRoute = BuilderWizardRouteImport.update({
  id: '/builder/wizard',
  path: '/builder/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderForgeRoute = BuilderForgeRouteImport.update({
  id: '/builder/forge',
  path: '/builder/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdRouteRoute = BotsBotIdRouteRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsBotIdIndexRoute = BotsBotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsBotIdRouteRoute,
} as any)
const BotsBotIdSoulRoute = BotsBotIdSoulRouteImport.update({
  id: '/soul',
  path: '/soul',
  getParentRoute: () => BotsBotIdRouteRoute,
} as any)
const BotsBotIdSkillsRoute = BotsBotIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => BotsBotIdRouteRoute,
} as any)
const BotsBotIdSettingsRoute = BotsBotIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BotsBotIdRouteRoute,
} as any)
const BotsBotIdChatRoute = BotsBotIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BotsBotIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/bots/$botId': typeof BotsBotIdRouteRouteWithChildren
  '/builder/forge': typeof BuilderForgeRoute
  '/builder/wizard': typeof BuilderWizardRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/bots/$botId/chat': typeof BotsBotIdChatRoute
  '/bots/$botId/settings': typeof BotsBotIdSettingsRoute
  '/bots/$botId/skills': typeof BotsBotIdSkillsRoute
  '/bots/$botId/soul': typeof BotsBotIdSoulRoute
  '/bots/$botId/': typeof BotsBotIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/builder/forge': typeof BuilderForgeRoute
  '/builder/wizard': typeof BuilderWizardRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/builder': typeof BuilderIndexRoute
  '/chat': typeof ChatIndexRoute
  '/bots/$botId/chat': typeof BotsBotIdChatRoute
  '/bots/$botId/settings': typeof BotsBotIdSettingsRoute
  '/bots/$botId/skills': typeof BotsBotIdSkillsRoute
  '/bots/$botId/soul': typeof BotsBotIdSoulRoute
  '/bots/$botId': typeof BotsBotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/bots/$botId': typeof BotsBotIdRouteRouteWithChildren
  '/builder/forge': typeof BuilderForgeRoute
  '/builder/wizard': typeof BuilderWizardRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/bots/$botId/chat': typeof BotsBotIdChatRoute
  '/bots/$botId/settings': typeof BotsBotIdSettingsRoute
  '/bots/$botId/skills': typeof BotsBotIdSkillsRoute
  '/bots/$botId/soul': typeof BotsBotIdSoulRoute
  '/bots/$botId/': typeof BotsBotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/bots/$botId'
    | '/builder/forge'
    | '/builder/wizard'
    | '/chat/$sessionId'
    | '/builder/'
    | '/chat/'
    | '/bots/$botId/chat'
    | '/bots/$botId/settings'
    | '/bots/$botId/skills'
    | '/bots/$botId/soul'
    | '/bots/$botId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/builder/forge'
    | '/builder/wizard'
    | '/chat/$sessionId'
    | '/builder'
    | '/chat'
    | '/bots/$botId/chat'
    | '/bots/$botId/settings'
    | '/bots/$botId/skills'
    | '/bots/$botId/soul'
    | '/bots/$botId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/bots/$botId'
    | '/builder/forge'
    | '/builder/wizard'
    | '/chat/$sessionId'
    | '/builder/'
    | '/chat/'
    | '/bots/$botId/chat'
    | '/bots/$botId/settings'
    | '/bots/$botId/skills'
    | '/bots/$botId/soul'
    | '/bots/$botId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BotsBotIdRouteRoute: typeof BotsBotIdRouteRouteWithChildren
  BuilderForgeRoute: typeof BuilderForgeRoute
  BuilderWizardRoute: typeof BuilderWizardRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/wizard': {
      id: '/builder/wizard'
      path: '/builder/wizard'
      fullPath: '/builder/wizard'
      preLoaderRoute: typeof BuilderWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/forge': {
      id: '/builder/forge'
      path: '/builder/forge'
      fullPath: '/builder/forge'
      preLoaderRoute: typeof BuilderForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/$botId/': {
      id: '/bots/$botId/'
      path: '/'
      fullPath: '/bots/$botId/'
      preLoaderRoute: typeof BotsBotIdIndexRouteImport
      parentRoute: typeof BotsBotIdRouteRoute
    }
    '/bots/$botId/soul': {
      id: '/bots/$botId/soul'
      path: '/soul'
      fullPath: '/bots/$botId/soul'
      preLoaderRoute: typeof BotsBotIdSoulRouteImport
      parentRoute: typeof BotsBotIdRouteRoute
    }
    '/bots/$botId/skills': {
      id: '/bots/$botId/skills'
      path: '/skills'
      fullPath: '/bots/$botId/skills'
      preLoaderRoute: typeof BotsBotIdSkillsRouteImport
      parentRoute: typeof BotsBotIdRouteRoute
    }
    '/bots/$botId/settings': {
      id: '/bots/$botId/settings'
      path: '/settings'
      fullPath: '/bots/$botId/settings'
      preLoaderRoute: typeof BotsBotIdSettingsRouteImport
      parentRoute: typeof BotsBotIdRouteRoute
    }
    '/bots/$botId/chat': {
      id: '/bots/$botId/chat'
      path: '/chat'
      fullPath: '/bots/$botId/chat'
      preLoaderRoute: typeof BotsBotIdChatRouteImport
      parentRoute: typeof BotsBotIdRouteRoute
    }
  }
}

interface BotsBotIdRouteRouteChildren {
  BotsBotIdChatRoute: typeof BotsBotIdChatRoute
  BotsBotIdSettingsRoute: typeof BotsBotIdSettingsRoute
  BotsBotIdSkillsRoute: typeof BotsBotIdSkillsRoute
  BotsBotIdSoulRoute: typeof BotsBotIdSoulRoute
  BotsBotIdIndexRoute: typeof BotsBotIdIndexRoute
}

const BotsBotIdRouteRouteChildren: BotsBotIdRouteRouteChildren = {
  BotsBotIdChatRoute: BotsBotIdChatRoute,
  BotsBotIdSettingsRoute: BotsBotIdSettingsRoute,
  BotsBotIdSkillsRoute: BotsBotIdSkillsRoute,
  BotsBotIdSoulRoute: BotsBotIdSoulRoute,
  BotsBotIdIndexRoute: BotsBotIdIndexRoute,
}

const BotsBotIdRouteRouteWithChildren = BotsBotIdRouteRoute._addFileChildren(
  BotsBotIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BotsBotIdRouteRoute: BotsBotIdRouteRouteWithChildren,
  BuilderForgeRoute: BuilderForgeRoute,
  BuilderWizardRoute: BuilderWizardRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
